### ISSUE TITLE
Make compatible with the new good reporter constructor

### ISSUE THREAD

**Issue by tom2strobl** [dmacosta/good-slack#13]
I think the latest `good` update (where you define the reporters as key/value pairs with piping arrays) destroyed `good-slack`. I used:

```
options: {
  ops: {
    interval: 60000
  },
  reporters: {
    slack: [{
      module: 'good-slack',
      name: 'GoodSlack', // if I omit this, it still doesn't work
      args: [{log: 'error', error: '*', response: 'error'}, {
        url: 'http://intentionallyhidden.com',
        format: 'YYYY-MM-DD/HH:mm:ss:SSS'
      }]
    }]
  }
}
```
which resulted in:
```
Error: Error in slack. good-slack must be a constructor function.
    at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/Users/thomas/dev/mindness/node_modules/hoek/lib/index.js:732:11)
    at /Users/thomas/dev/mindness/node_modules/good/lib/monitor.js:114:22
    at Object.__dirname.constructor.reducer._requestLogHandler._logHandler._errorHandler._responseHandler.start.internals.forOwn.internals.forOwn.stop.internals.forOwn.internals.forOwn.push.internals.forOwn [as forOwn] (/Users/thomas/dev/mindness/node_modules/good/lib/monitor.js:212:9)
    at Monitor.start (/Users/thomas/dev/mindness/node_modules/good/lib/monitor.js:94:19)
    at Object.exports.register (/Users/thomas/dev/mindness/node_modules/good/lib/index.js:42:20)
    at Object.target [as register] (/Users/thomas/dev/mindness/node_modules/hapi/node_modules/joi/lib/object.js:79:30)
    at each (/Users/thomas/dev/mindness/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/Users/thomas/dev/mindness/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/Users/thomas/dev/mindness/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at [object Object].module.exports.internals.Plugin.parent.auth.internals.Plugin.register.each [as register] (/Users/thomas/dev/mindness/node_modules/hapi/lib/plugin.js:320:11)
    at /Users/thomas/dev/mindness/node_modules/glue/lib/index.js:119:24
    at iterate (/Users/thomas/dev/mindness/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/Users/thomas/dev/mindness/node_modules/items/lib/index.js:39:9)
    at /Users/thomas/dev/mindness/node_modules/glue/lib/index.js:117:19
    at /Users/thomas/dev/mindness/node_modules/glue/lib/index.js:129:9
    at iterate (/Users/thomas/dev/mindness/node_modules/items/lib/index.js:36:13)
```

**Comment by dmacosta** [comment]
@tom2strobl Yeah, it seems the reporters interface has changed a lot on [good 7.0.0](https://github.com/hapijs/good/issues/467), so basically all reporters needs to stick to these changes otherwise breaks up as you find out. I've started working on some refactor (es6 + new reporter interface) while it was still optional, but dropped out since I've been playing around with something else. I'll try to take a look on this later. Thanks!

**Comment by dmacosta** [comment]
@tom2strobl I've just published `v3.0.0` for supporting `good@7.x.x`. Unfortunately I don't have much time to run some real world tests, so I relied 100% on the unit tests this time. If you've a chance to use the updated version let me know if you find any issue.

**Comment by tom2strobl** [comment]
I'll try it out the next couple of days. If I happen to find something, I'll keep you posted.
Thanks @dmacosta!

**Comment by tom2strobl** [comment]
Works like a charm. thanks

**Comment by dmacosta** [comment]
I'm glad to hear that. Thanks!

Get Outlook for iOS




On Sat, May 21, 2016 at 6:22 AM -0700, "Thomas Strobl" <notifications@github.com> wrote:












Works like a charm. thanks
